[package]
name = "ll-1"
version = "0.1.0"
authors = ["anyin233 <thenyyw@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "*"